### ISSUE TITLE
Load collectors from custom resource

### ISSUE THREAD

**Issue by cplee** [liatrio/rode#2]
Update [collector.go](https://github.com/liatrio/rode/blob/master/pkg/controller/collector.go) to load collectors from a new custom resource.  CRD should look like:

```
apiVersion: rode.liatr.io/v1alpha1
kind: Collector
spec:
  name: my_collector
  type: ecr_event
  queueName: my_ecr_event_queue
```
